Blast4-request ::= {
  body queue-search {
    program "blastn",
    service "plain",
    queries bioseq-set {
      seq-set {
        seq {
          id {
            local str "Query_165277"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">"
                }
              }
            }
          },
          inst {
            repr raw,
            mol na,
            length 30,
            seq-data ncbi2na '33B034C3893F13E0'H
          }
        }
      }
    },
    subject database "nr",
    algorithm-options {
      {
        name "EvalueThreshold",
        value cutoff e-value { 1, 10, 3 }
      },
      {
        name "UngappedMode",
        value boolean FALSE
      },
      {
        name "PercentIdentity",
        value real { 0, 10, 0 }
      },
      {
        name "HitlistSize",
        value integer 100
      },
      {
        name "EffectiveSearchSpace",
        value big-integer 0
      },
      {
        name "DbLength",
        value big-integer 0
      },
      {
        name "WindowSize",
        value integer 0
      },
      {
        name "DustFiltering",
        value boolean FALSE
      },
      {
        name "RepeatFiltering",
        value boolean FALSE
      },
      {
        name "MaskAtHash",
        value boolean FALSE
      },
      {
        name "MismatchPenalty",
        value integer -3
      },
      {
        name "MatchReward",
        value integer 1
      },
      {
        name "GapOpeningCost",
        value integer 5
      },
      {
        name "GapExtensionCost",
        value integer 2
      },
      {
        name "StrandOption",
        value strand-type both-strands
      },
      {
        name "WordSize",
        value integer 7
      }
    },
    program-options {
      {
        name "EntrezQuery",
        value string "phage[Title]"
      }
    },
    format-options {
      {
        name "Web_JobTitle",
        value string "NODE_6_length_212425_cov_256.954_meta_array_0"
      },
      {
        name "Web_EntrezQuery",
        value string "phage[Title]"
      },
      {
        name "Web_ShortQueryAdjust",
        value boolean TRUE
      }
    }
  }
}


